## begin license ##
#
# "Meresco Distributed" has components for group management based on "Meresco Components."
#
# Copyright (C) 2016 SURFmarket https://surf.nl
# Copyright (C) 2016 Seecr (Seek You Too B.V.) http://seecr.nl
#
# This file is part of "Meresco Distributed"
#
# "Meresco Distributed" is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# "Meresco Distributed" is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with "Meresco Distributed"; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
## end license ##

from seecr.test import SeecrTestCase, CallTrace
from meresco.distributed.failover import NginxConfigNG
from weightless.core import asString

class NginxConfigNGTest(SeecrTestCase):

    def testEmpty(self):
        top = NginxConfigNG()
        observer = CallTrace(methods=dict(servernames=lambda:(f for f in ['example.org'])), onlySpecifiedMethods=True)
        top.addObserver(observer)
        result = top.generate()
        self.assertEqualsWS('''## Generated by NginxConfig

server {
    server_name example.org;

    proxy_set_header    Host $host;
    proxy_set_header    X-Real-IP $remote_addr;
    proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;

    location / {
        location /unavailable.html {
        }
        return 503;
    }

    error_page 500 502 503 504 =503 /unavailable.html;
    location /unavailable.html {
        root /home/sharekit/meresco-distributed/usr-share/failover;
    }
    client_max_body_size 0;
}''', result)