#!/bin/bash
## begin license ##
#
# "NBC+" also known as "ZP (ZoekPlatform)" is
#  initiated by Stichting Bibliotheek.nl to provide a new search service
#  for all public libraries in the Netherlands.
# This package provides loadbalancer scripts
#
# Copyright (C) 2014 Seecr (Seek You Too B.V.) http://seecr.nl
# Copyright (C) 2014 Stichting Bibliotheek.nl (BNL) http://www.bibliotheek.nl
#
# This file is part of "NBC+ (Zoekplatform BNL) Loadbalancer"
#
# "NBC+ (Zoekplatform BNL) Loadbalancer" is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# "NBC+ (Zoekplatform BNL) Loadbalancer" is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with "NBC+ (Zoekplatform BNL) Loadbalancer"; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
## end license ##

source /usr/share/seecr-tools/functions.d/default
source /usr/share/seecr-tools/functions.d/svc

function show_usage {
    message "Usage $0 --ip <virtual ipaddress> [--name <service name>]"
}

TEMP=$(getopt \
    --options "" \
    --long ip::,name:: \
    -n "$0" -- "$@")

eval set -- "$TEMP"

while true ; do
    case "$1" in
        --ip)
            case "$2" in
                "")
                    show_usage
                    exit 1
                    ;;
                *)
                    IPADDR=$2
                    shift 2
                    ;;
            esac
            ;;
        --name)
            NAME=$2
            shift 2
            ;;
        --)
            shift
            break
            ;;
        *)
            echo "Unknown option specified."
            exit 1
            ;;
    esac
done

set -o errexit

if [ -z "$IPADDR" ]; then
    show_usage
    exit 1
fi

if [ -z "$NAME" ]; then
    NAME=${IPADDR}
fi

SERVICEDIR=/opt/zp-services
SERVICENAME="virtual-ip-${NAME}"
svc_create_service root root ${SERVICEDIR} "" ${SERVICENAME} "
sleepTimeSec=\$(( ( \$RANDOM % 5 )  + 1 ))
sleepTimeMinor=\$(( ( \$RANDOM % 100 )  + 1 ))
echo \"Sleeping \${sleepTimeSec}.\${sleepTimeMinor}s before starting\"
sleep \${sleepTimeSec}.\${sleepTimeMinor}s
exec ucarp-for-virt-ip --ip=${IPADDR}
"
svc_start_service ${SERVICEDIR} ${SERVICENAME}