#!/bin/bash
source /usr/share/seecr-tools/functions.d/default
source /usr/share/seecr-tools/functions.d/svc

function show_usage {
    message "Usage $0 --ip <virtual ipaddress> [--name <service name>]"
}

TEMP=$(getopt \
    --options "" \
    --long ip::,name:: \
    -n "$0" -- "$@")

eval set -- "$TEMP"

while true ; do
    case "$1" in
        --ip)
            case "$2" in
                "")
                    show_usage
                    exit 1
                    ;;
                *)
                    IPADDR=$2
                    shift 2
                    ;;
            esac
            ;;
        --name)
            NAME=$2
            shift 2
            ;;
        --)
            shift
            break
            ;;
        *)
            echo "Unknown option specified."
            exit 1
            ;;
    esac
done

set -o errexit

if [ -z "$IPADDR" ]; then
    show_usage
    exit 1
fi

if [ -z "$NAME" ]; then
    NAME=${IPADDR}
fi

SERVICEDIR=/opt/zp-services
SERVICENAME="virtual-ip-${NAME}"
svc_create_service root root ${SERVICEDIR} "" ${SERVICENAME} "
sleepTimeSec=\$(( ( \$RANDOM % 5 )  + 1 ))
sleepTimeMinor=\$(( ( \$RANDOM % 100 )  + 1 ))
echo \"Sleeping \${sleepTimeSec}.\${sleepTimeMinor}s before starting\"
sleep \${sleepTimeSec}.\${sleepTimeMinor}s
exec ucarp-for-virt-ip --ip=${IPADDR}
"
svc_start_service ${SERVICEDIR} ${SERVICENAME}