#!/bin/bash
## begin license ##
#
# "NBC+" also known as "ZP (ZoekPlatform)" is
#  initiated by Stichting Bibliotheek.nl to provide a new search service
#  for all public libraries in the Netherlands.
# This package provides loadbalancer scripts
#
# Copyright (C) 2014 Seecr (Seek You Too B.V.) http://seecr.nl
# Copyright (C) 2014 Stichting Bibliotheek.nl (BNL) http://www.bibliotheek.nl
#
# This file is part of "NBC+ (Zoekplatform BNL) Loadbalancer"
#
# "NBC+ (Zoekplatform BNL) Loadbalancer" is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# "NBC+ (Zoekplatform BNL) Loadbalancer" is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with "NBC+ (Zoekplatform BNL) Loadbalancer"; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
## end license ##

source /usr/share/seecr-tools/functions.d/default
source /usr/share/seecr-tools/functions.d/svc
source /usr/share/seecr-tools/functions.d/nginx

function show_usage {
    message "Usage $0 \\
        --type <service type> \\
        --ip <virtual ipaddress> \\
        --adminHostname <adminaddress> \\
        --minVersion <minimalVersion> \\
        --untilVersion <majorVersion of next release> \\
        [--adminPort 10000]
    Allowed service types: api, gateway, admin"
}

TEMP=$(getopt \
    --options "" \
    --long type::,ip::,adminIp::,adminPort::,minVersion::,untilVersion:: \
    -n "$0" -- "$@")

eval set -- "$TEMP"
ADMIN_PORT=10000

while true ; do
    case "$1" in
        --type)
            TYPE=$2; shift 2
            ;;
        --ip)
            IPADDR=$2; shift 2
            ;;
        --adminIp)
            ADMIN_IP=$2; shift 2
            ;;
        --adminPort)
            ADMIN_PORT=$2; shift 2
            ;;
        --minVersion)
            MIN_VERSION=$2; shift 2
            ;;
        --untilVersion)
            UNTIL_VERSION=$2; shift 2
            ;;
        --)
            shift
            break
            ;;
        *)
            echo "Unknown option specified."
            exit 1
            ;;
    esac
done

set -o errexit

for name in TYPE IPADDR ADMIN_IP MIN_VERSION UNTIL_VERSION; do
    if [ -z "${!name}" ]; then
        show_usage
        exit 1
    fi
done



function create_failover {
    SERVICEDIR=/opt/zp-services
    SERVICENAME="failover-${TYPE}"
    svc_create_service root root ${SERVICEDIR} "" ${SERVICENAME} "
exec nginx-update-config \\
    --adminHostname=$ADMIN_IP \\
    --adminPort=$ADMIN_PORT \\
    --type=${TYPE} \\
    --minVersion=${MIN_VERSION} \\
    --untilVersion=${UNTIL_VERSION}
"
    svc_prepare_service ${SERVICEDIR} ${SERVICENAME}
    nginx_restart
}

case $TYPE in
    api|gateway)
        create_failover
        ;;
    admin)
        ;;
    *)
        echo "Unknown type $TYPE"
        show_usage
        exit 1
        ;;
esac
