#!/bin/bash
## begin license ##
#
# "NBC+" also known as "ZP (ZoekPlatform)" is
#  a project of the Koninklijke Bibliotheek
#  and provides a search service for all public
#  libraries in the Netherlands.
# This package provides loadbalancer scripts
#
# Copyright (C) 2014, 2016 Seecr (Seek You Too B.V.) http://seecr.nl
# Copyright (C) 2014 Stichting Bibliotheek.nl (BNL) http://www.bibliotheek.nl
# Copyright (C) 2016 Koninklijke Bibliotheek (KB) http://www.kb.nl
#
# This file is part of "NBC+ (Zoekplatform BNL) Loadbalancer"
#
# "NBC+ (Zoekplatform BNL) Loadbalancer" is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# "NBC+ (Zoekplatform BNL) Loadbalancer" is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with "NBC+ (Zoekplatform BNL) Loadbalancer"; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
## end license ##

source /usr/share/seecr-tools/functions.d/default
source /usr/share/seecr-tools/functions.d/svc
source /usr/share/seecr-tools/functions.d/nginx
source /usr/share/seecr-tools/functions.d/iptables

mydir=$(cd $(dirname $0); pwd)
CD_BIN=""
CD_BIN="cd $(dirname $mydir)/bin" #DO_NOT_DISTRIBUTE
DOTSLASH=""
DOTSLASH="./" #DO_NOT_DISTRIBUTE

function show_usage {
    message "Usage $0 \\
        --type=<service type> \\
        --adminIp=<adminaddress> \\
        --minVersion=<minimalVersion> \\
        --untilVersion=<majorVersion of next release> \\
        [--ip=<virtual ipaddress> 'Only mandatory for type=admin'] \\
        [--name=<name for service, defaults to service type>] \\
        [--adminPort=10000]
        [--flag=<readable or writable>]
    Allowed service types: api, apikey, gateway, admin"
}

TEMP=$(getopt \
    --options "" \
    --long type::,name::,ip::,adminIp::,adminPort::,minVersion::,untilVersion:: \
    -n "$0" -- "$@")

eval set -- "$TEMP"
ADMIN_PORT=10000

while true ; do
    case "$1" in
        --type)
            TYPE=$2; shift 2
            ;;
        --name)
            NAME=$2; shift 2
            ;;
        --ip)
            IPADDR=$2; shift 2
            ;;
        --adminIp)
            ADMIN_IP=$2; shift 2
            ;;
        --adminPort)
            ADMIN_PORT=$2; shift 2
            ;;
        --minVersion)
            MIN_VERSION=$2; shift 2
            ;;
        --untilVersion)
            UNTIL_VERSION=$2; shift 2
            ;;
        --flag)
            FLAG=$2; shift 2
        --)
            shift
            break
            ;;
        *)
            echo "Unknown option specified."
            exit 1
            ;;
    esac
done

set -o errexit

for name in TYPE ADMIN_IP MIN_VERSION UNTIL_VERSION; do
    if [ -z "${!name}" ]; then
        show_usage
        exit 1
    fi
done

if [ "$TYPE" == "admin" ]; then
    if [ -z "$IPADDR" ]; then
        show_usage
        exit 1
    fi
fi

if [ -z "$NAME" ]; then
    NAME="$TYPE"
fi

if [ -z "$FLAG" ]; then
    FLAG=" \\
    --flag=$FLAG"
function create_failover {
    SERVICEDIR=/opt/zp-services
    SERVICENAME="failover-${NAME}"
    svc_create_service root root ${SERVICEDIR} "" ${SERVICENAME} "
${CD_BIN}
exec ${DOTSLASH}nginx-update-config \\
    --adminHostname=$ADMIN_IP \\
    --adminPort=$ADMIN_PORT \\
    --type=${TYPE} \\
    --name=${NAME} \\
    --minVersion=${MIN_VERSION} \\
    --untilVersion=${UNTIL_VERSION}$FLAG
"
    svc_prepare_service ${SERVICEDIR} ${SERVICENAME}
    nginx_restart

    iptables_open_port zp tcp 80
}

function create_admin_iptables_redirect {
    cat > /etc/seecr/firewall/rules.d/1-admin-zp <<EOF
#!/bin/bash
source /etc/seecr/firewall/config
\$IPTABLES -t nat -I PREROUTING -d $IPADDR -p tcp -j DNAT --to-destination $ADMIN_IP
EOF
    chmod +x /etc/seecr/firewall/rules.d/1-admin-zp
    invoke-rc.d seecr-firewall reload
}

case $TYPE in
    api|gateway|apikey)
        create_failover
        ;;
    admin)
        create_admin_iptables_redirect
        ;;
    *)
        echo "Unknown type $TYPE"
        show_usage
        exit 1
        ;;
esac
