## begin license ##
#
# "Meresco Distributed" has components for group management based on "Meresco Components."
#
# Copyright (C) 2016 SURFmarket https://surf.nl
# Copyright (C) 2016 Seecr (Seek You Too B.V.) http://seecr.nl
#
# This file is part of "Meresco Distributed"
#
# "Meresco Distributed" is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# "Meresco Distributed" is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with "Meresco Distributed"; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
## end license ##

from weightless.core import asList
from ._nginxconfig import _NginxConfig

class HttpToHttpsRedirect(_NginxConfig):
    def _generate(self, **kwargs):
        yield self.all.updateConfig(**kwargs)
        yield '## Generated by meresco.distributed.failover.HttpToHttpsRedirect\n\n'
        yield 'server {\n'
        yield self.all.listenLines()
        yield '    server_name '
        servernames = ' '.join(asList(self.all.servernames()))
        if not servernames:
            raise ValueError('Cannot generate config without servername.')
        yield servernames
        yield ';\n\n'
        yield '    rewrite  ^ https://{servername}$request_uri? permanent;\n'.format(servername=servernames.split(' ')[0])
        yield '}\n'

